"""Ordered-pair topology probes for PPro black-box calibration."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Sequence

from .errors import ValidationError
from .io import write_json
from .ppro_blackbox_runner import (
    MOCK_REPORT_PROFILE,
    RUN_SPEC_SCHEMA,
    SUPPORTED_REPORT_PROFILES,
    validate_run_spec,
)


_GENERATOR_ID = "ppro-blackbox-topology-reachability-v2"
_GENERATOR_REVISION = hashlib.sha256(_GENERATOR_ID.encode("utf-8")).hexdigest()
_EXPECTED_REPORTS = [
    "partition_summary",
    "resource_summary",
    "route_summary",
]


@dataclass(frozen=True)
class TopologyProbeBundle:
    root: Path
    rtl_path: Path
    filelist_path: Path
    parameters_path: Path
    constraints_path: Path
    run_spec_path: Path
    run_spec: Dict[str, Any]


def _canonical(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _topology_rtl(width: int, pipeline_stages: int) -> str:
    return f"""// Generated by {_GENERATOR_ID}; logical partitions are mapped at runtime.
module calibration_producer (
    input wire clk,
    input wire reset_n,
    input wire [{width - 1}:0] seed,
    output reg [{width - 1}:0] payload
);
    always @(posedge clk) begin
        if (!reset_n) payload <= seed;
        else payload <= {{payload[{width - 2}:0], payload[{width - 1}] ^ payload[1] ^ payload[0]}};
    end
endmodule

module calibration_consumer (
    input wire clk,
    input wire reset_n,
    input wire [{width - 1}:0] payload,
    output wire digest
);
    (* keep = "true", dont_touch = "yes", shreg_extract = "no" *)
    reg [{width - 1}:0] pipeline [0:{pipeline_stages - 1}];
    integer index;
    always @(posedge clk) begin
        if (!reset_n) begin
            for (index = 0; index < {pipeline_stages}; index = index + 1)
                pipeline[index] <= {{{width}{{1'b0}}}};
        end else begin
            pipeline[0] <= payload;
            for (index = 1; index < {pipeline_stages}; index = index + 1)
                pipeline[index] <= pipeline[index - 1] ^ index;
        end
    end
    assign digest = ^pipeline[{pipeline_stages - 1}];
endmodule

module ppro_blackbox_topology_probe (
    input wire clk,
    input wire reset_n,
    input wire [{width - 1}:0] seed,
    output wire digest
);
    wire [{width - 1}:0] transported_payload;
    calibration_producer P0 (.clk(clk), .reset_n(reset_n), .seed(seed), .payload(transported_payload));
    calibration_consumer P1 (.clk(clk), .reset_n(reset_n), .payload(transported_payload), .digest(digest));
endmodule
"""


def generate_topology_probe_bundle(
    output_dir: Path,
    *,
    fpga_count: int,
    source_index: int,
    sink_index: int,
    width: int,
    pipeline_stages: int,
    repeat: int,
    role: str,
    campaign_id: str,
    public_prior_id: str,
    configuration_id: str,
    tool_release: str,
    runner_revision: str,
    seed: int,
    adapter_profile: str = MOCK_REPORT_PROFILE,
) -> TopologyProbeBundle:
    if adapter_profile not in SUPPORTED_REPORT_PROFILES:
        raise ValidationError("topology adapter profile is unsupported")
    for name, value, minimum in (
        ("fpga_count", fpga_count, 2),
        ("width", width, 1),
        ("pipeline_stages", pipeline_stages, 2),
        ("repeat", repeat, 0),
        ("seed", seed, 0),
    ):
        if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
            raise ValidationError(f"topology {name} must be an integer >= {minimum}")
    if not 0 <= source_index < fpga_count or not 0 <= sink_index < fpga_count:
        raise ValidationError("topology source and sink indices must select configured FPGAs")
    if source_index == sink_index:
        raise ValidationError("topology probe requires different source and sink FPGAs")

    root = output_dir.resolve()
    root.mkdir(parents=True, exist_ok=True)
    rtl_path = root / "topology_probe.v"
    filelist_path = root / "sources.f"
    parameters_path = root / "parameters.json"
    constraints_path = root / "documented_constraints.json"
    run_spec_path = root / "run-spec.json"
    rtl = _topology_rtl(width, pipeline_stages)
    rtl_path.write_text(rtl, encoding="utf-8")
    filelist_path.write_text("topology_probe.v\n", encoding="utf-8")
    parameters = {
        "fpga_count": fpga_count,
        "generator": _GENERATOR_ID,
        "pipeline_stages": pipeline_stages,
        "sink_index": sink_index,
        "source_index": source_index,
        "width": width,
    }
    constraints = {
        "assignments": [
            {"partition": "P0", "target": f"F{source_index}"},
            {"partition": "P1", "target": f"F{sink_index}"},
        ],
        "control_mode": "fixed_assignment",
        "documented_actions": ["partition_constraint"],
        "seed": seed,
    }
    write_json(parameters_path, parameters, compact=True)
    write_json(constraints_path, constraints, compact=True)
    case_id = f"topology-f{source_index}-f{sink_index}-w{width}-r{repeat}"
    spec = {
        "schema": RUN_SPEC_SCHEMA,
        "identity": {
            "id": f"{campaign_id}.{case_id}",
            "campaign_id": campaign_id,
            "case_id": case_id,
            "role": role,
            "public_prior_id": public_prior_id,
            "configuration_id": configuration_id,
        },
        "tool": {
            "name": "PPro",
            "release": tool_release,
            "runner_revision": runner_revision,
        },
        "workload": {
            "generator_id": _GENERATOR_ID,
            "generator_revision": _GENERATOR_REVISION,
            "rtl_sha256": _sha256(rtl.encode("utf-8")),
            "parameters_sha256": _sha256(_canonical(parameters)),
            "top_module": "ppro_blackbox_topology_probe",
            "design_metrics": {
                "fpga_count": fpga_count,
                "pipeline_stages": pipeline_stages,
                "probe_width_bits": width,
                "sink_fpga_index": sink_index,
                "source_fpga_index": source_index,
            },
        },
        "experiment": {
            "kind": "topology_reachability",
            "control_mode": "fixed_assignment",
            "documented_actions": constraints["documented_actions"],
            "constraints_sha256": _sha256(_canonical(constraints)),
        },
        "execution": {"seed": seed},
        "adapter": {
            "profile": adapter_profile,
            "expected_reports": _EXPECTED_REPORTS,
        },
    }
    normalized = validate_run_spec(spec)
    write_json(run_spec_path, normalized, compact=True)
    return TopologyProbeBundle(
        root=root,
        rtl_path=rtl_path,
        filelist_path=filelist_path,
        parameters_path=parameters_path,
        constraints_path=constraints_path,
        run_spec_path=run_spec_path,
        run_spec=normalized,
    )


def generate_ordered_pair_matrix(
    output_dir: Path,
    *,
    fpga_count: int,
    holdout_pairs: Sequence[tuple[int, int]],
    repeats: int,
    width: int,
    pipeline_stages: int,
    campaign_id: str,
    public_prior_id: str,
    configuration_id: str,
    tool_release: str,
    runner_revision: str,
    seed_base: int = 1,
    adapter_profile: str = MOCK_REPORT_PROFILE,
) -> list[TopologyProbeBundle]:
    if repeats < 1:
        raise ValidationError("topology matrix repeats must be >= 1")
    holdouts = set(holdout_pairs)
    legal_pairs = {(source, sink) for source in range(fpga_count) for sink in range(fpga_count) if source != sink}
    if not holdouts <= legal_pairs:
        raise ValidationError("topology holdout pair is outside the configured FPGA set")
    if not holdouts:
        raise ValidationError("topology matrix requires at least one holdout ordered pair")
    bundles = []
    for source, sink in sorted(legal_pairs):
        for repeat in range(repeats):
            bundles.append(
                generate_topology_probe_bundle(
                    output_dir / f"f{source}-f{sink}" / "fit" / f"r{repeat}",
                    fpga_count=fpga_count,
                    source_index=source,
                    sink_index=sink,
                    width=width,
                    pipeline_stages=pipeline_stages,
                    repeat=repeat,
                    role="fit",
                    campaign_id=campaign_id,
                    public_prior_id=public_prior_id,
                    configuration_id=configuration_id,
                    tool_release=tool_release,
                    runner_revision=runner_revision,
                    seed=seed_base + repeat,
                    adapter_profile=adapter_profile,
                )
            )
        if (source, sink) in holdouts:
            for repeat in range(repeats):
                bundles.append(
                    generate_topology_probe_bundle(
                        output_dir / f"f{source}-f{sink}" / "holdout" / f"r{repeat}",
                        fpga_count=fpga_count,
                        source_index=source,
                        sink_index=sink,
                        width=width,
                        pipeline_stages=pipeline_stages,
                        repeat=repeats + repeat,
                        role="holdout",
                        campaign_id=campaign_id,
                        public_prior_id=public_prior_id,
                        configuration_id=configuration_id,
                        tool_release=tool_release,
                        runner_revision=runner_revision,
                        seed=seed_base + repeats + repeat,
                        adapter_profile=adapter_profile,
                    )
                )
    return bundles
