"""Controlled communication probes for bandwidth, TDM, latency, and cost."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Sequence

from .errors import ValidationError
from .io import write_json
from .ppro_blackbox_runner import (
    MOCK_REPORT_PROFILE,
    RUN_SPEC_SCHEMA,
    SUPPORTED_REPORT_PROFILES,
    validate_run_spec,
)


COMMUNICATION_KINDS = {"payload_capacity", "latency", "transport_cost"}
_GENERATOR_ID = "ppro-blackbox-communication-probe-v2"
_GENERATOR_REVISION = hashlib.sha256(_GENERATOR_ID.encode("utf-8")).hexdigest()
_EXPECTED_REPORTS = [
    "partition_summary",
    "resource_summary",
    "route_summary",
    "system_timing",
]


@dataclass(frozen=True)
class CommunicationProbeBundle:
    root: Path
    rtl_path: Path
    filelist_path: Path
    parameters_path: Path
    constraints_path: Path
    run_spec_path: Path
    run_spec: Dict[str, Any]


def _positive_unique(values: Sequence[int], name: str) -> tuple[int, ...]:
    normalized = tuple(values)
    if (
        not normalized
        or any(isinstance(value, bool) or not isinstance(value, int) or value <= 0 for value in normalized)
        or len(normalized) != len(set(normalized))
    ):
        raise ValidationError(f"communication matrix {name} must be unique positive integers")
    return normalized


def _canonical(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _communication_rtl(width: int, flow_count: int, fanout: int, bidirectional: bool) -> str:
    total_width = width * flow_count
    source_update = (
        "payload ^ return_payload"
        if total_width == 1
        else f"{{payload[{total_width - 2}:0], payload[{total_width - 1}] ^ payload[1] ^ payload[0] ^ ^return_payload}}"
    )
    ack_update = (
        "payload"
        if total_width == 1
        else f"payload ^ {{payload[{total_width - 2}:0], payload[{total_width - 1}]}}"
    )
    consumer_instances = []
    ack_wires = []
    for index in range(fanout):
        ack_wires.append(f"    wire [{total_width - 1}:0] ack_{index};")
        consumer_instances.append(
            f"    calibration_sink P{index + 1} (.clk(clk), .reset_n(reset_n), "
            f".payload(payload), .ack(ack_{index}), .digest(digest_bus[{index}]));"
        )
    if bidirectional:
        ack_expression = " ^ ".join(f"ack_{index}" for index in range(fanout))
        ack_connection = f"wire [{total_width - 1}:0] return_payload = {ack_expression};"
    else:
        ack_connection = f"wire [{total_width - 1}:0] return_payload = {{{total_width}{{1'b0}}}};"
    return f"""// Generated by {_GENERATOR_ID}; logical endpoints are mapped at runtime.
module calibration_source (
    input wire clk,
    input wire reset_n,
    input wire [{total_width - 1}:0] return_payload,
    output reg [{total_width - 1}:0] payload
);
    always @(posedge clk) begin
        if (!reset_n) payload <= {{{total_width}{{1'b1}}}};
        else payload <= {source_update};
    end
endmodule

module calibration_sink (
    input wire clk,
    input wire reset_n,
    input wire [{total_width - 1}:0] payload,
    output reg [{total_width - 1}:0] ack,
    output wire digest
);
    always @(posedge clk) begin
        if (!reset_n) ack <= {{{total_width}{{1'b0}}}};
        else ack <= {ack_update};
    end
    assign digest = ^ack;
endmodule

module ppro_blackbox_communication_probe (
    input wire clk,
    input wire reset_n,
    output wire digest
);
    wire [{total_width - 1}:0] payload;
{chr(10).join(ack_wires)}
    wire [{fanout - 1}:0] digest_bus;
    {ack_connection}
    calibration_source P0 (.clk(clk), .reset_n(reset_n),
                           .return_payload(return_payload), .payload(payload));
{chr(10).join(consumer_instances)}
    assign digest = ^digest_bus;
endmodule
"""


def generate_communication_probe_bundle(
    output_dir: Path,
    *,
    kind: str,
    fpga_count: int,
    source_index: int,
    sink_indices: Sequence[int],
    width: int,
    flow_count: int,
    bidirectional: bool,
    local_baseline: bool,
    forced_tdm_ratio: int,
    repeat: int,
    role: str,
    campaign_id: str,
    public_prior_id: str,
    configuration_id: str,
    tool_release: str,
    runner_revision: str,
    seed: int,
    adapter_profile: str = MOCK_REPORT_PROFILE,
) -> CommunicationProbeBundle:
    if kind not in COMMUNICATION_KINDS:
        raise ValidationError(f"communication kind must be one of {sorted(COMMUNICATION_KINDS)}")
    if adapter_profile not in SUPPORTED_REPORT_PROFILES:
        raise ValidationError("communication adapter profile is unsupported")
    if adapter_profile != MOCK_REPORT_PROFILE and forced_tdm_ratio:
        raise ValidationError(
            "real PPro forced-TDM probes require a documented provider constraint syntax"
        )
    for name, value, minimum in (
        ("fpga_count", fpga_count, 2),
        ("width", width, 1),
        ("flow_count", flow_count, 1),
        ("forced_tdm_ratio", forced_tdm_ratio, 0),
        ("repeat", repeat, 0),
        ("seed", seed, 0),
    ):
        if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
            raise ValidationError(f"communication {name} must be an integer >= {minimum}")
    if type(bidirectional) is not bool or type(local_baseline) is not bool:
        raise ValidationError("communication direction and baseline flags must be boolean")
    sinks = tuple(sink_indices)
    if not sinks or len(sinks) != len(set(sinks)):
        raise ValidationError("communication sink indices must be unique and non-empty")
    if not 0 <= source_index < fpga_count or any(sink < 0 or sink >= fpga_count for sink in sinks):
        raise ValidationError("communication endpoints must select distinct configured FPGAs")
    if local_baseline:
        if kind != "transport_cost" or any(sink != source_index for sink in sinks):
            raise ValidationError("local baseline requires transport_cost endpoints on one FPGA")
    elif any(sink == source_index for sink in sinks):
        raise ValidationError("communication endpoints must select distinct configured FPGAs")

    root = output_dir.resolve()
    root.mkdir(parents=True, exist_ok=True)
    rtl_path = root / "communication_probe.v"
    filelist_path = root / "sources.f"
    parameters_path = root / "parameters.json"
    constraints_path = root / "documented_constraints.json"
    run_spec_path = root / "run-spec.json"
    rtl = _communication_rtl(width, flow_count, len(sinks), bidirectional)
    rtl_path.write_text(rtl, encoding="utf-8")
    filelist_path.write_text("communication_probe.v\n", encoding="utf-8")
    parameters = {
        "bidirectional": bidirectional,
        "flow_count": flow_count,
        "fpga_count": fpga_count,
        "generator": _GENERATOR_ID,
        "local_baseline": local_baseline,
        "sink_indices": list(sinks),
        "source_index": source_index,
        "width": width,
    }
    actions = ["partition_constraint"]
    if forced_tdm_ratio:
        actions.append("tdm_ratio_constraint")
    constraints = {
        "assignments": [
            {"partition": "P0", "target": f"F{source_index}"},
            *[
                {"partition": f"P{index + 1}", "target": f"F{sink}"}
                for index, sink in enumerate(sinks)
            ],
        ],
        "control_mode": "fixed_assignment",
        "documented_actions": sorted(actions),
        "forced_tdm_ratio": forced_tdm_ratio,
        "seed": seed,
    }
    write_json(parameters_path, parameters, compact=True)
    write_json(constraints_path, constraints, compact=True)
    case_id = (
        f"{kind}-f{source_index}-s{'-'.join(str(value) for value in sinks)}"
        f"-w{width}-n{flow_count}-b{int(bidirectional)}-t{forced_tdm_ratio}-r{repeat}"
    )
    spec = {
        "schema": RUN_SPEC_SCHEMA,
        "identity": {
            "id": f"{campaign_id}.{case_id}",
            "campaign_id": campaign_id,
            "case_id": case_id,
            "role": role,
            "public_prior_id": public_prior_id,
            "configuration_id": configuration_id,
        },
        "tool": {
            "name": "PPro",
            "release": tool_release,
            "runner_revision": runner_revision,
        },
        "workload": {
            "generator_id": _GENERATOR_ID,
            "generator_revision": _GENERATOR_REVISION,
            "rtl_sha256": _sha256(rtl.encode("utf-8")),
            "parameters_sha256": _sha256(_canonical(parameters)),
            "top_module": "ppro_blackbox_communication_probe",
            "design_metrics": {
                "bidirectional": int(bidirectional),
                "endpoint_count": 1 + len(sinks),
                "fanout": len(sinks),
                "flow_count": flow_count,
                "forced_tdm_ratio": forced_tdm_ratio,
                "local_baseline": int(local_baseline),
                "probe_width_bits": width,
                "repeat_index": repeat,
                "sink_fpga_index": sinks[0],
                "source_fpga_index": source_index,
            },
        },
        "experiment": {
            "kind": kind,
            "control_mode": "fixed_assignment",
            "documented_actions": sorted(actions),
            "constraints_sha256": _sha256(_canonical(constraints)),
        },
        "execution": {"seed": seed},
        "adapter": {
            "profile": adapter_profile,
            "expected_reports": (
                _EXPECTED_REPORTS
                if kind == "latency"
                else ["partition_summary", "resource_summary", "route_summary"]
                if kind == "payload_capacity"
                else ["partition_summary", "resource_summary"]
            ),
        },
    }
    normalized = validate_run_spec(spec)
    write_json(run_spec_path, normalized, compact=True)
    return CommunicationProbeBundle(
        root=root,
        rtl_path=rtl_path,
        filelist_path=filelist_path,
        parameters_path=parameters_path,
        constraints_path=constraints_path,
        run_spec_path=run_spec_path,
        run_spec=normalized,
    )


def generate_communication_matrix(
    output_dir: Path,
    *,
    kind: str,
    fpga_count: int,
    source_index: int,
    sink_indices: Sequence[int],
    fit_widths: Sequence[int],
    holdout_widths: Sequence[int],
    flow_counts: Sequence[int],
    bidirectional: bool,
    repeats: int,
    campaign_id: str,
    public_prior_id: str,
    configuration_id: str,
    tool_release: str,
    runner_revision: str,
    seed_base: int,
    adapter_profile: str = MOCK_REPORT_PROFILE,
) -> list[CommunicationProbeBundle]:
    """Generate a bounded fit/holdout matrix with paired transport baselines."""

    fit = _positive_unique(fit_widths, "fit_widths")
    holdout = _positive_unique(holdout_widths, "holdout_widths")
    flows = _positive_unique(flow_counts, "flow_counts")
    if set(fit) & set(holdout):
        raise ValidationError("communication fit and holdout widths must be disjoint")
    if isinstance(repeats, bool) or not isinstance(repeats, int) or repeats < 2:
        raise ValidationError("communication matrix repeats must be an integer >= 2")
    if isinstance(seed_base, bool) or not isinstance(seed_base, int) or seed_base < 0:
        raise ValidationError("communication matrix seed_base must be a nonnegative integer")
    sinks = tuple(sink_indices)
    if kind == "transport_cost" and len(sinks) != 1:
        raise ValidationError("transport-cost matrix requires exactly one cross-FPGA sink")

    bundles: list[CommunicationProbeBundle] = []
    for role, widths in (("fit", fit), ("holdout", holdout)):
        for width in widths:
            for flow_count in flows:
                for repeat in range(repeats):
                    common = {
                        "kind": kind,
                        "fpga_count": fpga_count,
                        "source_index": source_index,
                        "width": width,
                        "flow_count": flow_count,
                        "bidirectional": bidirectional,
                        "forced_tdm_ratio": 0,
                        "repeat": repeat,
                        "role": role,
                        "campaign_id": campaign_id,
                        "public_prior_id": public_prior_id,
                        "configuration_id": configuration_id,
                        "tool_release": tool_release,
                        "runner_revision": runner_revision,
                        "seed": seed_base + repeat,
                        "adapter_profile": adapter_profile,
                    }
                    point = f"{role}/w{width}/n{flow_count}/r{repeat}"
                    if kind == "transport_cost":
                        bundles.append(
                            generate_communication_probe_bundle(
                                output_dir / point / "local",
                                sink_indices=[source_index],
                                local_baseline=True,
                                **common,
                            )
                        )
                    bundles.append(
                        generate_communication_probe_bundle(
                            output_dir / point / "cross",
                            sink_indices=sinks,
                            local_baseline=False,
                            **common,
                        )
                    )
    return bundles
