"""Deterministic connected smoke workload for the PPro black-box boundary.

The generated bundle is intentionally provider-neutral.  It contains RTL, a
file list, public experiment parameters, and a redacted run specification.  A
runtime-only binding is responsible for selecting an authorized PPro platform,
license environment, command, and report locations.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict

from .errors import ValidationError
from .io import write_json
from .ppro_blackbox_runner import (
    MOCK_REPORT_PROFILE,
    RUN_SPEC_SCHEMA,
    SUPPORTED_REPORT_PROFILES,
    validate_run_spec,
)


_GENERATOR_ID = "ppro-blackbox-connected-smoke-v3"
_GENERATOR_REVISION = hashlib.sha256(_GENERATOR_ID.encode("utf-8")).hexdigest()
_REPORTS = [
    "partition_summary",
    "resource_summary",
    "route_summary",
    "system_timing",
]


@dataclass(frozen=True)
class GeneratedSmokeBundle:
    root: Path
    rtl_path: Path
    filelist_path: Path
    include_path: Path
    compilation_context_path: Path
    parameters_path: Path
    constraints_path: Path
    run_spec_path: Path
    run_spec: Dict[str, Any]


def _canonical_bytes(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _connected_smoke_rtl(width: int, pipeline_stages: int) -> str:
    return f"""// Generated by {_GENERATOR_ID}; provider-neutral calibration RTL.
`include "connected_smoke_context.vh"

module ppro_blackbox_smoke_producer (
    input  wire                 clk,
    input  wire                 reset_n,
    input  wire [{width - 1}:0] seed,
    output reg  [{width - 1}:0] payload
);
    reg [{width - 1}:0] state;
    always @(posedge clk) begin
        if (!reset_n) begin
            state <= seed;
            payload <= seed;
        end else begin
            state <= {{state[{width - 2}:0],
                      state[{width - 1}] ^ state[{width - 2}] ^ state[1] ^ state[0]}};
            payload <= state ^ seed ^
                       (`PPRO_SMOKE_HEADER_PRESENT &&
                        (`PPRO_SMOKE_WIDTH == {width}));
        end
    end
endmodule

module ppro_blackbox_smoke_consumer (
    input  wire                 clk,
    input  wire                 reset_n,
    input  wire [{width - 1}:0] payload,
    output wire [{width - 1}:0] digest
);
    (* keep = "true", dont_touch = "yes", shreg_extract = "no" *)
    reg [{width - 1}:0] pipeline [0:{pipeline_stages - 1}];
    integer index;
    always @(posedge clk) begin
        if (!reset_n) begin
            for (index = 0; index < {pipeline_stages}; index = index + 1)
                pipeline[index] <= {{{width}{{1'b0}}}};
        end else begin
            pipeline[0] <= payload;
            for (index = 1; index < {pipeline_stages}; index = index + 1)
                pipeline[index] <= pipeline[index - 1] + index;
        end
    end

    assign digest = pipeline[{pipeline_stages - 1}];
endmodule

module ppro_blackbox_connected_smoke (
    input  wire                 clk,
    input  wire                 reset_n,
    input  wire [{width - 1}:0] seed,
    output wire [{width - 1}:0] digest
);
    wire [{width - 1}:0] transported_payload;

    ppro_blackbox_smoke_producer P0 (
        .clk(clk), .reset_n(reset_n), .seed(seed), .payload(transported_payload)
    );
    ppro_blackbox_smoke_consumer P1 (
        .clk(clk), .reset_n(reset_n), .payload(transported_payload), .digest(digest)
    );
endmodule
"""


def _compilation_identity(
    rtl_path: Path, include_path: Path, *, width: int
) -> Dict[str, Any]:
    root = rtl_path.parent
    rtl_inputs = {
        "source_records": [
            {
                "path": rtl_path.relative_to(root).as_posix(),
                "sha256": _sha256_bytes(rtl_path.read_bytes()),
                "size": rtl_path.stat().st_size,
            }
        ],
        "include_file_records": [
            {
                "path": include_path.relative_to(root).as_posix(),
                "sha256": _sha256_bytes(include_path.read_bytes()),
                "size": include_path.stat().st_size,
            }
        ],
        "include_dirs": ["context"],
        "defines": [f"PPRO_SMOKE_WIDTH={width}"],
    }
    return {
        "rtl_sha256": _sha256_bytes(_canonical_bytes(rtl_inputs)),
        "rtl_inputs": rtl_inputs,
    }


def generate_connected_smoke_bundle(
    output_dir: Path,
    *,
    campaign_id: str,
    case_id: str,
    public_prior_id: str,
    configuration_id: str,
    tool_release: str,
    runner_revision: str,
    seed: int = 1,
    width: int = 32,
    pipeline_stages: int = 8,
    role: str = "holdout",
    adapter_profile: str = MOCK_REPORT_PROFILE,
) -> GeneratedSmokeBundle:
    """Generate one idempotent C0 smoke bundle without runtime secrets.

    C0 fixes one producer and one consumer to different logical FPGAs through
    the independently validated public ``assign_inst`` syntax. This guarantees
    that the smoke exercises partition, route, and timing report production,
    while its holdout role prevents it from becoming fitting evidence.
    """
    if isinstance(width, bool) or not isinstance(width, int) or width < 8:
        raise ValidationError("connected smoke width must be an integer >= 8")
    if (
        isinstance(pipeline_stages, bool)
        or not isinstance(pipeline_stages, int)
        or pipeline_stages < 2
    ):
        raise ValidationError("connected smoke pipeline_stages must be an integer >= 2")
    if isinstance(seed, bool) or not isinstance(seed, int) or seed < 0:
        raise ValidationError("connected smoke seed must be an integer >= 0")
    if adapter_profile not in SUPPORTED_REPORT_PROFILES:
        raise ValidationError("connected smoke adapter profile is unsupported")

    root = output_dir.resolve()
    root.mkdir(parents=True, exist_ok=True)
    rtl_path = root / "connected_smoke.v"
    include_dir = root / "context"
    include_dir.mkdir(exist_ok=True)
    include_path = include_dir / "connected_smoke_context.vh"
    filelist_path = root / "sources.f"
    compilation_context_path = root / "compilation-context.json"
    parameters_path = root / "parameters.json"
    constraints_path = root / "documented_constraints.json"
    run_spec_path = root / "run-spec.json"

    rtl = _connected_smoke_rtl(width, pipeline_stages)
    rtl_path.write_text(rtl, encoding="utf-8")
    include_path.write_text(
        "// Compile-context sentinel for the connected PPro smoke.\n"
        "`define PPRO_SMOKE_HEADER_PRESENT 1\n",
        encoding="utf-8",
    )
    filelist_path.write_text("connected_smoke.v\n", encoding="utf-8")
    compilation_identity = _compilation_identity(
        rtl_path, include_path, width=width
    )
    write_json(
        compilation_context_path,
        {
            "schema": "emuflow.ppro-compilation-context/v1",
            "source_root": str(root),
            "include_dirs": compilation_identity["rtl_inputs"]["include_dirs"],
            "defines": compilation_identity["rtl_inputs"]["defines"],
        },
        compact=True,
    )

    parameters = {
        "generator": _GENERATOR_ID,
        "pipeline_stages": pipeline_stages,
        "width": width,
    }
    constraints = {
        "assignments": [
            {"partition": "P0", "target": "F0"},
            {"partition": "P1", "target": "F1"},
        ],
        "control_mode": "fixed_assignment",
        "documented_actions": ["partition_constraint"],
        "seed": seed,
    }
    write_json(parameters_path, parameters, compact=True)
    write_json(constraints_path, constraints, compact=True)

    spec = {
        "schema": RUN_SPEC_SCHEMA,
        "identity": {
            "id": f"{campaign_id}.{case_id}.seed{seed}",
            "campaign_id": campaign_id,
            "case_id": case_id,
            "role": role,
            "public_prior_id": public_prior_id,
            "configuration_id": configuration_id,
        },
        "tool": {
            "name": "PPro",
            "release": tool_release,
            "runner_revision": runner_revision,
        },
        "workload": {
            "generator_id": _GENERATOR_ID,
            "generator_revision": _GENERATOR_REVISION,
            "rtl_sha256": compilation_identity["rtl_sha256"],
            "parameters_sha256": _sha256_bytes(_canonical_bytes(parameters)),
            "top_module": "ppro_blackbox_connected_smoke",
            "design_metrics": {
                "pipeline_stages": pipeline_stages,
                "rtl_width": width,
            },
        },
        "experiment": {
            "kind": "reproducibility",
            "control_mode": "fixed_assignment",
            "documented_actions": ["partition_constraint"],
            "constraints_sha256": _sha256_bytes(_canonical_bytes(constraints)),
        },
        "execution": {"seed": seed},
        "adapter": {
            "profile": adapter_profile,
            "expected_reports": _REPORTS,
        },
    }
    normalized = validate_run_spec(spec)
    write_json(run_spec_path, normalized, compact=True)
    return GeneratedSmokeBundle(
        root=root,
        rtl_path=rtl_path,
        filelist_path=filelist_path,
        include_path=include_path,
        compilation_context_path=compilation_context_path,
        parameters_path=parameters_path,
        constraints_path=constraints_path,
        run_spec_path=run_spec_path,
        run_spec=normalized,
    )
