"""Deterministic connected smoke workload for the PPro black-box boundary.

The generated bundle is intentionally provider-neutral.  It contains RTL, a
file list, public experiment parameters, and a redacted run specification.  A
runtime-only binding is responsible for selecting an authorized PPro platform,
license environment, command, and report locations.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict

from .errors import ValidationError
from .io import write_json
from .ppro_blackbox_runner import MOCK_REPORT_PROFILE, RUN_SPEC_SCHEMA, validate_run_spec


_GENERATOR_ID = "ppro-blackbox-connected-smoke-v1"
_GENERATOR_REVISION = hashlib.sha256(_GENERATOR_ID.encode("utf-8")).hexdigest()
_REPORTS = [
    "partition_summary",
    "resource_summary",
    "route_summary",
    "system_timing",
]


@dataclass(frozen=True)
class GeneratedSmokeBundle:
    root: Path
    rtl_path: Path
    filelist_path: Path
    parameters_path: Path
    constraints_path: Path
    run_spec_path: Path
    run_spec: Dict[str, Any]


def _canonical_bytes(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _connected_smoke_rtl(width: int, pipeline_stages: int) -> str:
    return f"""// Generated by {_GENERATOR_ID}; provider-neutral calibration RTL.
module ppro_blackbox_connected_smoke (
    input  wire                 clk,
    input  wire                 reset_n,
    input  wire [{width - 1}:0] seed,
    output wire [{width - 1}:0] digest
);
    reg [{width - 1}:0] state;
    reg [{width - 1}:0] pipeline [0:{pipeline_stages - 1}];
    integer index;

    always @(posedge clk) begin
        if (!reset_n) begin
            state <= seed;
            for (index = 0; index < {pipeline_stages}; index = index + 1)
                pipeline[index] <= {{{width}{{1'b0}}}};
        end else begin
            state <= {{state[{width - 2}:0],
                      state[{width - 1}] ^ state[{width - 2}] ^ state[1] ^ state[0]}};
            pipeline[0] <= state ^ seed;
            for (index = 1; index < {pipeline_stages}; index = index + 1)
                pipeline[index] <= pipeline[index - 1] + index;
        end
    end

    assign digest = pipeline[{pipeline_stages - 1}] ^ state;
endmodule
"""


def generate_connected_smoke_bundle(
    output_dir: Path,
    *,
    campaign_id: str,
    case_id: str,
    public_prior_id: str,
    configuration_id: str,
    tool_release: str,
    runner_revision: str,
    seed: int = 1,
    width: int = 32,
    pipeline_stages: int = 8,
    role: str = "holdout",
) -> GeneratedSmokeBundle:
    """Generate one idempotent C0 smoke bundle without runtime secrets.

    C0 is deliberately unconstrained: it verifies ordinary project execution
    and report availability, not hardware fitting.  Fixed-assignment and
    fixed-communication constraints are introduced only by later calibration
    stages after their documented PPro syntax is independently validated.
    """
    if isinstance(width, bool) or not isinstance(width, int) or width < 8:
        raise ValidationError("connected smoke width must be an integer >= 8")
    if (
        isinstance(pipeline_stages, bool)
        or not isinstance(pipeline_stages, int)
        or pipeline_stages < 2
    ):
        raise ValidationError("connected smoke pipeline_stages must be an integer >= 2")
    if isinstance(seed, bool) or not isinstance(seed, int) or seed < 0:
        raise ValidationError("connected smoke seed must be an integer >= 0")

    root = output_dir.resolve()
    root.mkdir(parents=True, exist_ok=True)
    rtl_path = root / "connected_smoke.v"
    filelist_path = root / "sources.f"
    parameters_path = root / "parameters.json"
    constraints_path = root / "documented_constraints.json"
    run_spec_path = root / "run-spec.json"

    rtl = _connected_smoke_rtl(width, pipeline_stages)
    rtl_path.write_text(rtl, encoding="utf-8")
    filelist_path.write_text("connected_smoke.v\n", encoding="utf-8")

    parameters = {
        "generator": _GENERATOR_ID,
        "pipeline_stages": pipeline_stages,
        "width": width,
    }
    constraints = {
        "control_mode": "none",
        "documented_actions": [],
        "seed": seed,
    }
    write_json(parameters_path, parameters, compact=True)
    write_json(constraints_path, constraints, compact=True)

    spec = {
        "schema": RUN_SPEC_SCHEMA,
        "identity": {
            "id": f"{campaign_id}.{case_id}.seed{seed}",
            "campaign_id": campaign_id,
            "case_id": case_id,
            "role": role,
            "public_prior_id": public_prior_id,
            "configuration_id": configuration_id,
        },
        "tool": {
            "name": "PPro",
            "release": tool_release,
            "runner_revision": runner_revision,
        },
        "workload": {
            "generator_id": _GENERATOR_ID,
            "generator_revision": _GENERATOR_REVISION,
            "rtl_sha256": _sha256_bytes(rtl.encode("utf-8")),
            "parameters_sha256": _sha256_bytes(_canonical_bytes(parameters)),
            "design_metrics": {
                "pipeline_stages": pipeline_stages,
                "rtl_width": width,
            },
        },
        "experiment": {
            "kind": "reproducibility",
            "control_mode": "none",
            "documented_actions": [],
            "constraints_sha256": _sha256_bytes(_canonical_bytes(constraints)),
        },
        "execution": {"seed": seed},
        "adapter": {
            "profile": MOCK_REPORT_PROFILE,
            "expected_reports": _REPORTS,
        },
    }
    normalized = validate_run_spec(spec)
    write_json(run_spec_path, normalized, compact=True)
    return GeneratedSmokeBundle(
        root=root,
        rtl_path=rtl_path,
        filelist_path=filelist_path,
        parameters_path=parameters_path,
        constraints_path=constraints_path,
        run_spec_path=run_spec_path,
        run_spec=normalized,
    )
