"""Check the emitted physical asynchronous-assert/synchronous-release chain.

Structural evidence only. Recovery/removal, analog metastability and board
reset pulse width are not certified by inspecting a routed connectivity graph.
"""
from .errors import ValidationError


def qualify_snapshot_reset_annotations(routed, delays, *, top="top"):
    """Require physical release-chain data timing without inventing recovery.

    The asynchronous assertion pins intentionally do not receive setup/hold
    constraints. Their recovery/removal and metastability behavior require a
    separate device/external contract; data annotations cannot prove those.
    """
    structure = qualify_snapshot_reset_structure(routed, top=top)
    if delays.get('delay_connectivity_checked') is not True:
        raise ValidationError('reset annotation check requires connectivity-checked delays')
    first, second = structure['first_cell'], structure['second_cell']
    cell = routed['modules'][top]['cells'][second]
    data = 'DI' if str(cell['parameters']['SD']).strip() == '1' else 'M'
    wire = delays.get('interconnect', {}).get(((first, 'Q'), (second, data)))
    cq = delays.get('cells', {}).get(first, {}).get('iopaths', {}).get(('CLK', 'Q'))
    checks = delays.get('cells', {}).get(second, {}).get('setuphold', {})
    setuphold = [checks.get(((edge, data), ('posedge', 'CLK')))
                 for edge in ('posedge', 'negedge')]
    if wire is None or cq is None or any(v is None for v in setuphold):
        raise ValidationError('missing reset release interstage timing annotation')
    return dict(structure, scope='physical_reset_structure_and_release_annotation',
        interstage=dict(clock_to_q_min_ns=min(v[0] for v in cq),
            clock_to_q_max_ns=max(v[2] for v in cq),
            wire_min_ns=min(v[0] for v in wire), wire_max_ns=max(v[2] for v in wire),
            setup_max_ns=max(v[0][2] for v in setuphold),
            hold_max_ns=max(v[1][2] for v in setuphold)),
        release_data_timing_qualified=False,
        asynchronous_assertion_policy='no_fabricated_recovery_removal_constraint')


def qualify_snapshot_reset_structure(routed, *, top="top"):
    module=routed.get("modules",{}).get(top)
    if not isinstance(module,dict): raise ValidationError("missing reset physical top")
    cells=module.get("cells",{}); nets=module.get("netnames",{})

    def scalar(bits):
        if not isinstance(bits,list) or len(bits)!=1 or type(bits[0]) is not int or bits[0]<0:
            raise ValidationError("reset structure requires scalar physical wire")
        return bits[0]

    def connection(cell,port):
        return scalar(cell.get("connections",{}).get(port))

    drivers={}; consumers={}
    for name,cell in cells.items():
        for port,bits in cell.get("connections",{}).items():
            if not bits: continue
            direction=cell.get("port_directions",{}).get(port)
            if direction not in {"input","output","inout"}:
                raise ValidationError("missing reset physical port direction")
            for bit in bits:
                if type(bit) is not int: continue
                (drivers if direction=="output" else consumers).setdefault(bit,set()).add((name,port))

    def driver(bit,kind,port):
        candidates=drivers.get(bit,set())
        if len(candidates)!=1: raise ValidationError("reset wire has no unique driver")
        name,p=next(iter(candidates)); cell=cells[name]
        if p!=port or cell.get("type")!=kind:
            raise ValidationError("unexpected reset driver primitive")
        return name,cell

    # These root aliases are generated by snapshot_pair's physical wrapper.
    q0=scalar(nets.get("reset_pipe[0]",{}).get("bits"))
    q1=scalar(nets.get("reset",{}).get("bits"))
    first,f=driver(q0,"TRELLIS_FF","Q"); second,s=driver(q1,"TRELLIS_FF","Q")
    if first==second: raise ValidationError("reset release stages merged")
    data=[]
    for cell in (f,s):
        params=cell.get("parameters",{})
        if any(str(params.get(k,"")).strip()!=v for k,v in {
                "SRMODE":"ASYNC","REGSET":"SET","CLKMUX":"CLK",
                "LSRMUX":"LSR","CEMUX":"1","GSR":"DISABLED"}.items()):
            raise ValidationError("reset chain semantics changed")
        sd=str(params.get("SD","")).strip()
        if sd not in {"0","1"}: raise ValidationError("unknown reset FF packing")
        data.append("DI" if sd=="1" else "M")
    if connection(f,"CLK")!=connection(s,"CLK") or connection(f,"LSR")!=connection(s,"LSR"):
        raise ValidationError("reset stages do not share clock/assertion")
    if connection(s,data[1])!=q0 or consumers.get(q0)!={(second,data[1])}:
        raise ValidationError("reset first stage bypass or additional fanout")
    zero=f.get("connections",{}).get(data[0])
    if zero!=["0"]:
        _,const=driver(scalar(zero),"TRELLIS_COMB","F")
        if const.get("parameters",{}).get("MODE","LOGIC")!="LOGIC" or const.get("parameters",{}).get("INITVAL")!="0"*16:
            raise ValidationError("reset first stage must shift a constant zero")
    asserted=connection(f,"LSR")
    if consumers.get(asserted)!={(first,"LSR"),(second,"LSR")}:
        raise ValidationError("raw asynchronous assertion bypasses release chain")
    _,inv=driver(asserted,"TRELLIS_COMB","F")
    inputs=[(p,b) for p,b in inv.get("connections",{}).items() if p in "ABCD" and b]
    if len(inputs)!=1 or inv.get("parameters",{}).get("MODE","LOGIC")!="LOGIC":
        raise ValidationError("reset polarity must be a unary LUT inverter")
    pin,bits=inputs[0]; wire=scalar(bits)
    expected=''.join(str(1-((i>>"ABCD".index(pin))&1)) for i in reversed(range(16)))
    if inv.get("parameters",{}).get("INITVAL")!=expected:
        raise ValidationError("reset inverter truth table mismatch")
    padname,pad=driver(wire,"TRELLIS_IO","O")
    port=module.get("ports",{}).get("reset_n",{})
    if (port.get("direction")!="input" or pad.get("parameters",{}).get("DIR")!="INPUT"
            or connection(pad,"B")!=scalar(port.get("bits"))):
        raise ValidationError("reset chain is not driven by reset_n pad")
    invname=next(iter(drivers[asserted]))[0]
    if consumers.get(wire)!={(invname,pin)}:
        raise ValidationError("external reset bypasses polarity/release chain")
    asynchronous={n for n,c in cells.items() if c.get("type")=="TRELLIS_FF" and c.get("parameters",{}).get("SRMODE")=="ASYNC"}
    if asynchronous!={first,second}:
        raise ValidationError("asynchronous state outside the reset release chain")
    return {"status":"pass","scope":"physical_reset_assert_release_structure",
            "pad_cell":padname,"first_cell":first,"second_cell":second,
            "recovery_removal_qualified":False,"metastability_mtbf_qualified":False,
            "external_reset_pulse_qualified":False,"global_timing_qualified":False}
